#!/usr/bin/env node
// Downloads voiceover clips generated by Claude via the ElevenLabs connector.
// Usage: node scripts/fetch-voice.mjs <id>      (reads out/<id>/audio/urls.json)
// urls.json: { "voice_id": "...", "expires_at": "...", "clips": { "s01": "https://...", ... } }
import fs from 'node:fs';
import path from 'node:path';

const id = process.argv[2];
if (!id) { console.error('usage: node scripts/fetch-voice.mjs <id>'); process.exit(1); }
const root = path.resolve(new URL('..', import.meta.url).pathname);
const dir = path.join(root, 'out', id, 'audio');
const manifest = JSON.parse(fs.readFileSync(path.join(dir, 'urls.json'), 'utf8'));

let ok = 0, fail = 0;
for (const [step, url] of Object.entries(manifest.clips)) {
  const dest = path.join(dir, `${step}.mp3`);
  try {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HTTP ${res.status}${res.status === 400 || res.status === 403 ? ' – signed URL expired? ask Claude to refresh urls.json' : ''}`);
    fs.writeFileSync(dest, Buffer.from(await res.arrayBuffer()));
    console.log(`✓ ${step} ${(fs.statSync(dest).size / 1024).toFixed(0)} kB`); ok++;
  } catch (e) { console.error(`✗ ${step}: ${e.message}`); fail++; }
}
console.log(`\n${ok} ok, ${fail} failed → ${dir}`);
process.exit(fail ? 1 : 0);
