#!/usr/bin/env node
// Downloads voiceover clips generated by Claude via the ElevenLabs connector.
// Usage: node scripts/fetch-voice.mjs <id>      (reads out/<id>/audio/urls.json)
// urls.json: { "voice_id": "...", "expires_at": "...", "clips": { "s01": "https://...", ... },
//              "texts": { "s01": "<exact text that was voiced>", ... } }   (texts optional)
// With `texts`, every clip is checked against audio/manifest.json `tts_text` (= narration_tts ?? narration)
// so a clip voiced from the subtitle / an old narration is reported instead of silently accepted.
import fs from 'node:fs';
import path from 'node:path';

const id = process.argv[2];
if (!id) { console.error('usage: node scripts/fetch-voice.mjs <id>'); process.exit(1); }
const root = path.resolve(new URL('..', import.meta.url).pathname);
const dir = path.join(root, 'out', id, 'audio');
const manifest = JSON.parse(fs.readFileSync(path.join(dir, 'urls.json'), 'utf8'));

let expected = null;
try { expected = Object.fromEntries(JSON.parse(fs.readFileSync(path.join(dir, 'manifest.json'), 'utf8')).steps.map((s) => [s.id, s.tts_text ?? s.narration])); } catch { /* no manifest yet */ }
const norm = (s) => String(s ?? '').trim().replace(/\s+/g, ' ');
let mismatch = 0;
if (manifest.texts && expected) {
  for (const [step, text] of Object.entries(manifest.texts)) {
    if (expected[step] !== undefined && norm(expected[step]) !== norm(text)) {
      console.error(`! ${step}: clip was voiced from a different text than tts_text\n    voiced:   "${norm(text).slice(0, 100)}"\n    expected: "${norm(expected[step]).slice(0, 100)}"`);
      mismatch++;
    }
  }
} else if (!manifest.texts) console.log('note: urls.json has no "texts" – cannot check that clips match tts_text (narration_tts ?? narration)');

let ok = 0, fail = 0;
for (const [step, url] of Object.entries(manifest.clips)) {
  const dest = path.join(dir, `${step}.mp3`);
  try {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HTTP ${res.status}${res.status === 400 || res.status === 403 ? ' – signed URL expired? ask Claude to refresh urls.json' : ''}`);
    fs.writeFileSync(dest, Buffer.from(await res.arrayBuffer()));
    console.log(`✓ ${step} ${(fs.statSync(dest).size / 1024).toFixed(0)} kB`); ok++;
  } catch (e) { console.error(`✗ ${step}: ${e.message}`); fail++; }
}
console.log(`\n${ok} ok, ${fail} failed${mismatch ? `, ${mismatch} voiced from the wrong text` : ''} → ${dir}`);
process.exit(fail || mismatch ? 1 : 0);
