#!/usr/bin/env bash
# Idempotent setup on a colleague's Mac, without admin rights or Homebrew.
# Installs Node 22, pnpm, ffmpeg + ffprobe into ~/.onboarding-videos (override: SVP_TOOLS_DIR),
# then the repo dependencies and Playwright Chromium. Writes ~/.onboarding-videos/env.sh;
# every pipeline command runs as:  source ~/.onboarding-videos/env.sh && <command>
# Prints only variable NAMES from .env, never values.
set -u
cd "$(dirname "$0")/.."
REPO="$PWD"
T="${SVP_TOOLS_DIR:-$HOME/.onboarding-videos}"
mkdir -p "$T/bin"
[ "$(uname -s)" = "Darwin" ] || { echo "✗ local-setup.sh is for macOS (in a cloud session use scripts/cloud-setup.sh)"; exit 1; }
case "$(uname -m)" in arm64) ARCH=arm64 ;; x86_64) ARCH=x64 ;; *) echo "✗ unsupported CPU $(uname -m)"; exit 1 ;; esac
export PATH="$T/bin:$T/node/bin:$PATH"

echo "== Node 22"
node_ok() { command -v node >/dev/null 2>&1 && [ "$(node -p 'process.versions.node.split(".")[0]')" -ge 22 ] 2>/dev/null; }
if node_ok; then echo "  ✓ node $(node -v)"
else
  V=$(curl -fsSL https://nodejs.org/dist/index.json | /usr/bin/python3 -c 'import json,sys; print(next(r["version"] for r in json.load(sys.stdin) if r["version"].startswith("v22.")))' 2>/dev/null) \
    || { echo "  ✗ cannot reach nodejs.org"; exit 1; }
  rm -rf "$T/node" "$T/node.tmp" && mkdir -p "$T/node.tmp"
  curl -fsSL "https://nodejs.org/dist/$V/node-$V-darwin-$ARCH.tar.gz" | tar -xz -C "$T/node.tmp" --strip-components 1 \
    && mv "$T/node.tmp" "$T/node" && echo "  ✓ node $V installed" || { echo "  ✗ node download failed"; exit 1; }
fi

echo "== pnpm, ffmpeg, ffprobe"
PNPM_V=$(node -p 'require("./package.json").packageManager.split("@")[1]')
if [ ! -x "$T/tools/node_modules/.bin/pnpm" ] || [ ! -f "$T/tools/node_modules/ffmpeg-static/ffmpeg" ] || [ "$("$T/tools/node_modules/.bin/pnpm" -v 2>/dev/null)" != "$PNPM_V" ]; then
  mkdir -p "$T/tools" && [ -f "$T/tools/package.json" ] || echo '{"private":true}' > "$T/tools/package.json"
  (cd "$T/tools" && npm install --silent --no-fund --no-audit "pnpm@$PNPM_V" ffmpeg-static@5 @ffprobe-installer/ffprobe@2) >/tmp/svp-tools.log 2>&1 \
    || { tail -15 /tmp/svp-tools.log; echo "  ✗ tool install failed"; exit 1; }
fi
FF="$T/tools/node_modules/ffmpeg-static/ffmpeg"
FP=$(cd "$T/tools" && node -p 'require("@ffprobe-installer/ffprobe").path')
ln -sf "$T/tools/node_modules/.bin/pnpm" "$T/bin/pnpm"; ln -sf "$FF" "$T/bin/ffmpeg"; ln -sf "$FP" "$T/bin/ffprobe"
"$T/bin/ffmpeg" -hide_banner -encoders 2>/dev/null | grep -q libx264 && echo "  ✓ ffmpeg (x264) / ffprobe / pnpm $PNPM_V" || { echo "  ✗ ffmpeg broken"; exit 1; }
cat > "$T/env.sh" <<EOF
# generated by scripts/local-setup.sh
export PATH="$T/bin:$T/node/bin:\$PATH"
export FFMPEG_PATH="$T/bin/ffmpeg"
export FFPROBE_PATH="$T/bin/ffprobe"
EOF
. "$T/env.sh"

echo "== repo dependencies"
if pnpm install --frozen-lockfile >/tmp/svp-install.log 2>&1; then echo "  ✓ pnpm install"; else tail -15 /tmp/svp-install.log; echo "  ✗ pnpm install failed"; exit 1; fi

echo "== Playwright Chromium"
if pnpm --filter @svp/recorder exec playwright install chromium >/tmp/svp-playwright.log 2>&1; then echo "  ✓ chromium"
else tail -15 /tmp/svp-playwright.log; echo "  ✗ chromium download failed"; exit 1; fi

echo "== login (.env)"
if [ ! -f "$REPO/.env" ]; then
  sed 's#^SLONEEK_DEMO_URL=.*#SLONEEK_DEMO_URL=https://app-pre-production.sloneek.com#' "$REPO/.env.example" > "$REPO/.env"
  echo "  · .env created"
fi
missing=()
for v in SLONEEK_DEMO_URL SLONEEK_DEMO_USER SLONEEK_DEMO_PASS; do
  grep -Eq "^$v=.+" "$REPO/.env" && echo "  ✓ $v" || { echo "  ✗ $v empty"; missing+=("$v"); }
done
if [ ${#missing[@]} -gt 0 ]; then echo "SETUP NEEDS LOGIN: fill ${missing[*]} in $REPO/.env"; exit 3; fi
echo "SETUP OK  (prefix commands with: source $T/env.sh && …)"
