export { tts, linearAlignment, sayArgs, sayConfig, parseSayVoices, chooseProvider, SAY_DEFAULT_VOICE, SAY_DEFAULT_RATE } from "./tts.js";
export type { TtsOptions, TtsResult, Alignment, Provider } from "./tts.js";
export { mux, INTRO_MS, OUTRO_MS, INTERSTITIAL_MS, fontFile } from "./mux.js";
export { ttsText, subtitleText, effectiveParts, partStarts, chaptersText, chapterProblems, ytTime } from "./parts.js";
export type { Chapter, PartStart } from "./parts.js";
export type { MuxOptions, MuxResult } from "./mux.js";
export { splitNarration, cuesForStep, toSrt, mapTextIndices } from "./srt.js";
export { probeDurationMs } from "./util.js";
export { writeManifest, buildManifest, acceptExternal, classifyStep, parseAlignment, findExternalAudio } from "./external.js";
export type { Manifest, ManifestStep } from "./external.js";
